server:
  port: 8111

spring:
  application:
    name: server

  datasource:
    url: jdbc:mysql://localhost:3309/ecommercedb
    username: root
    password: root

  jpa:
    show-sql: true

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "backend-ecommerce"
    description: "System Ecommerce"
    version: "1.0.0"
