server:
  port: 8111

spring:
  application:
    name: server
  cloud:
    config:
      enabled: false
    import-check:
      enabled: false

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: "http://localhost:8080/realms/master/protocol/openid-connect/certs"

#  main:
#    allow-bean-definition-overriding: true

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/base
    username: root
    password: 1234

  jpa:
    show-sql: true

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: "backend-ecommerce"
    description: "System Ecommerce"
    version: "1.0.0"
